import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";



export default function Home() {
  const router = useRouter();
  const [latitude, setLatitude] = useState<number | null>(null);
  const [longitude, setLongitude] = useState<number | null>(null);
  const [radius, setRadius] = useState<number>(3);

  const getCurrentLocation = () => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        setLatitude(position.coords.latitude);
        setLongitude(position.coords.longitude);
      });
    } else {
      alert('Geolocation is not supported by this browser.');
    }
  };

  const chooseRadius = (radius: number) => {
    setRadius(radius);
  }

  const handleSearch = () => {

    router.push({
      pathname: '/search',
      query: {
        latitude: latitude,
        longitude: longitude,
        range: radius
      }
    });
  }

  return (
    <>
      <Head>
        <title>Near GOHAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Near GOHAN</h1>
        <button onClick={getCurrentLocation}>Get Current Location</button>
        <div>
          Latitude: {latitude}, Longitude: {longitude}
        </div>
        <div>
          <button onClick={handleSearch}>Search</button>
        </div>
      </main>
    </>
  );
}
